repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: 'frontend/'
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^(.github/|data/|docs/|frontend/|infra/|backend/users/migrations)/
        additional_dependencies:
          - pyproject-flake8
          - flake8-builtins
          - flake8-bugbear
          - flake8-quotes
          - flake8-eradicate
          - flake8-mock
          - flake8-pie
          - flake8-print
          - flake8-printf-formatting
          - flake8-pytest-style
          - flake8-variables-names
        args: ['--config=setup.cfg']
