repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: 'frontend/'
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
    -   id: isort
        exclude: ^(.github/|data/|docs/|frontend/|infra)/
        args: [--project, 'exceptions', -p, 'config']
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(.github/|data/|docs/|frontend/|infra/)/
        args: [-S, -t, py37, --line-length, '79']
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: ^(.github/|data/|docs/|frontend/|infra/|backend/users/migrations)/
        additional_dependencies:
          - pyproject-flake8
          - flake8-builtins
          - flake8-bugbear
          - flake8-quotes
          - flake8-eradicate
          - flake8-mock
          - flake8-pie
          - flake8-print
          - flake8-printf-formatting
          - flake8-pytest-style
          - flake8-variables-names
        args: ['--config=setup.cfg']
