# Generated by Django 3.2 on 2023-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="text",
            field=models.CharField(max_length=5000, verbose_name="Описание"),
        ),
    ]
